name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: pnpm build && pnpm exec electron-builder --linux --publish always

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: pnpm build && pnpm exec electron-builder --mac --publish always
        env:
          CSC_LINK: ${{ secrets.MAC_CERTIFICATE }}
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: pnpm build && pnpm exec electron-builder --win --publish always
